#!/bin/bash

p=$(readlink $0) || p=$0
d=$(dirname  $p)
b=$(basename $p)

test -n "$SMS__JAVA" && java="$SMS__JAVA" || java="java"
test -n "$SMS__RUBY" &&  mri="$SMS__RUBY" ||  mri="ruby"
jruby="$java -server -jar $d/jruby.jar" # last tested: Java 21 + JRuby 10

engine="$jruby" # set to either $mri or $jruby

$engine $d/$b.rb $@
