#!/usr/bin/env ruby

$: << (basedir=File.dirname(File.expand_path($0))) << File.join(basedir,"lib")

require 'treetop'
require 'sms_normfree'
require 'sms_fortran'
require 'translator'

include Translator

go

# paul.a.madden@noaa.gov
