#!/usr/bin/env ruby

threads=8

require "fileutils"
require 'thread'

def docmd(cmd)
  out=IO.popen(cmd+" 2>&1") { |x| x.readlines.reduce("") { |s,e| s+=e } }
  [($?.exitstatus==0)?(true):(false),out]
end

def exe(bin)
  cmd=bin
  stat,out=docmd(cmd)
  fail(out,cmd) unless stat
  out
end

def fail(msg=nil,cmd=nil)
  puts
  puts "Command: #{cmd}" if cmd
  puts msg if msg
  puts "FAIL"
  exit(1)
end

def run(q)
  test(q.deq) until q.empty?
end

def test(t)
  print "."
  exe("make -C #{t} clean")
  exe("make -C #{t} exe")
  e="./a.out"
  stdout=((File.exist?(File.join(t,e)))?(exe("cd #{t} && #{e}")):(""))
  f=File.join(t,"control")
  if File.exist?(f)
    control=File.open(f,"rb").read
    unless stdout==control
      msg="#{t} output expected:\n--begin--\n"
      msg+=control
      msg+="-- end --\n#{t} output actual:\n--begin--\n"
      msg+=stdout
      msg+="-- end --"
      fail msg
    end
  end
  exe("make -C #{t} clean")
end

fail "Need at least one thread to run tests" unless threads>0
exe("make")
tdir="tests"
tests=(ARGV[0])?(["#{tdir}/#{ARGV[0]}"]):(Dir.glob("#{tdir}/t*").sort)
q=Queue.new
tests.each { |e| q.enq(e) }
(1..threads).reduce([]) { |m,e| m << Thread.new { run(q) } }.each { |e| e.join }
puts "\nOK (#{tests.size} tests)"

# paul.a.madden@noaa.gov
