# Autogenerated from a Treetop grammar. Edits may be lost.


require "normfixed_parser"

module Normfixed
  include Treetop::Runtime

end

class NormfixedParser < Treetop::Runtime::CompiledParser
  include Normfixed
end

